modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/GeyserMC/Hurricane/"
[[mods]]
modId="hurricane"
version="$version"
displayName="$name"
displayURL="$url"
logoFile= "../assets/hurricane/icon.png"
authors="GeyserMC"
description="$description"
[[mixins]]
config = "hurricane.mixins.json"
[[dependencies.hurricane]]
modId="neoforge"
type="required"
versionRange="[21.3.0-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.hurricane]]
modId="minecraft"
type="required"
versionRange="[$1.21.3,)"
ordering="NONE"
side="BOTH"
[[dependencies.hurricane]]
modId="floodgate"
type="optional"
ordering="AFTER"
versionRange="[2.2.3-SNAPSHOT,)"
side="BOTH"
[[dependencies.hurricane]]
modId="geyser_neoforge"
versionRange="[2.3.2-SNAPSHOT,)"
type="optional"
ordering="AFTER"
side="BOTH"